version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:16.13.1
      
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

workflows:
  default:
    jobs:
      - build-frontend:
          filters:
            branches:
              only: [staging]
