name: Deploy staging server to REMOTE HOST

on:
  pull_request:
    types: [closed]
    branches:
      - staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Frontend to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          username: ${{secrets.USER}}

          script: |
            cd app
            git checkout dev
            git pull
